baseURL = "https://guardianhubx.com/blog/"
#relativeURLs = false
#canonifyURLs = true
languageCode = "es-es"
title = "GuardianHubX Blog"
theme = "PaperMod"
publishDir = "public"
uglyURLs = false
[pagination]
  pagerSize = 10

[params]
  env = "production"
  defaultTheme = "light"
  showReadingTime = true
  disableThemeToggle = true
  mainSections = ["blog"]

[params.assets]
  disableFingerprinting = true
  favicon = "/favicon.ico"
  customCSS = ["css/custom.css"]
  customJS = [
    "https://code.jquery.com/jquery-3.6.0.min.js",
    "js/load-common.js"
  ]
  googleFonts = ["Poppins"]