baseURL       = "https://guardianhubx.com/blog/"
relativeURLs  = false
canonifyURLs  = true

languageCode  = "es-es"
title         = "GuardianHubX Blog"
theme         = "PaperMod"
publishDir    = "public"
uglyURLs      = false

[pagination]
  pagerSize = 10
  path      = "blog/page"

# Genera URL /blog/:slug/ para todos los contenidos en content/blog
[permalinks]
  blog = "/:slug/"

[params]
  env                = "production"
  defaultTheme       = "light"       # Fondo blanco
  showReadingTime    = true
  disableThemeToggle = true
  mainSections       = ["blog"]

[params.assets]
  disableFingerprinting = true
  favicon               = "/favicon.ico"
  customCSS             = ["css/custom.css"]
  customJS              = []
  googleFonts           = ["Poppins"]