baseURL                       = "https://guardianhubx.com/blog/"
languageCode                  = "es-es"
defaultContentLanguage        = "es"
defaultContentLanguageInSubdir = false
relativeURLs                  = false
canonifyURLs                  = true
title                         = "GuardianHubX Blog"
theme                         = "PaperMod"
publishDir                    = "public"
uglyURLs                      = false

[pagination]
  pagerSize = 10

[languages]

  [languages.es]
    languageName = "Español"
    weight       = 1
    contentDir   = "content/es"
    title        = "GuardianHubX Blog"
    
    [languages.es.params]
      mainSections = ["blog"]
    
    [languages.es.permalinks]
      blog = "/blog/:slug/"

  [languages.ca]
    languageName = "Català"
    weight       = 2
    contentDir   = "content/ca"
    title        = "GuardianHubX Blog – en català"
    
    [languages.ca.params]
      mainSections = ["blog"]
    
    [languages.ca.permalinks]
      blog = "/blog/ca/:slug/"

[params]
  env                = "production"
  defaultTheme       = "light"
  showReadingTime    = true
  disableThemeToggle = true
  mainSections       = ["blog"]

[params.assets]
  disableFingerprinting = true
  favicon               = "/favicon.ico"
  customCSS             = ["css/custom.css"]
  customJS              = []
  googleFonts           = ["Poppins"]

[outputs]
  home    = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]