baseURL = "https://guardianhubx.com/blog/"
relativeURLs = false
canonifyURLs = true
defaultContentLanguage    = "es"
defaultContentLanguageInSubdir = false
languageCode = "es-es"
title = "GuardianHubX Blog"
theme = "PaperMod"
publishDir = "public"
uglyURLs = false

[languages]
  [languages.es]
    languageName = "Español"
    weight       = 1

    [languages.es.pagination]
      pagerSize = 10
      path      = "page"

[params]
  env = "production"
  defaultTheme = "light" # Fondo blanco
  showReadingTime = true
  disableThemeToggle = true # No permitir cambiar a modo oscuro
  mainSections = ["blog"]

[params.assets]
  disableFingerprinting = true
  favicon = "/favicon.ico"
  customCSS = ["css/custom.css"]
  customJS = []
  googleFonts = ["Poppins"]