name: Daily Scheduled Deploy (main site)

on:
  schedule:
    # 06:05 Europa/Madrid (estiu = UTC+2) -> 04:05 UTC
    - cron: "5 4 * * *"
  workflow_dispatch: {}

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Notify main repo to deploy
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.MAIN_REPO_TOKEN }}
          repository: Qualiteasy-Internet-Solutions/guardianhubx.github.io
          event-type: blog-updated
